version: "3.9"

services:
  postgresDB:
    container_name: postgresql
    image: postgres:15.4-alpine3.18
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adm_psql
      POSTGRES_DB: customer
      PGDATA: /data/postgres
    ports:
      - "8000:5432"
    networks:
      - ecommerce-network
    restart: unless-stopped
  mysqlDB:
    container_name: mysql
    image: mysql:8.0.34-oracle
    environment:
      MYSQL_ROOT_PASSWORD: adm_mysql
      MYSQL_DATABASE: fraud
      PGDATA: /data/mysql
    ports:
      - "8050:3306"
    networks:
      - ecommerce-network
    restart: always
networks:
  ecommerce-network: